# Generated by Django 2.2 on 2019-05-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='album',
        ),
    ]
