# Generated by Django 2.2 on 2019-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='album',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
